### ISSUE TITLE
Need some clarity

### ISSUE THREAD

**Issue by oleteacher** [ronisaha/easy-merge2pdf#2]
Thanks for sharing this!

I see this is example:

1,3-8,2,1

Does this mean: add pages 1-3, single page 8 and 2, then all page 1 again?

Just want to be clear for using in classroom project.

**Comment by ronisaha** [comment]
No, It implies, Page 1 first Then Page 3-8, then page 2 and then page 1 again. So actually it become: 1,3,4,5,6,7,8,2,1
